#if !canImport(ObjectiveC)
import XCTest

extension ArgumentParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArgumentParserTests = [
        ("testBasics", testBasics),
        ("testBinderThrows", testBinderThrows),
        ("testBoolParsing", testBoolParsing),
        ("testErrors", testErrors),
        ("testIntParsing", testIntParsing),
        ("testOptionalPositionalArg", testOptionalPositionalArg),
        ("testOptions", testOptions),
        ("testPathArgument", testPathArgument),
        ("testRemainingStrategy", testRemainingStrategy),
        ("testShellCompletionGeneration", testShellCompletionGeneration),
        ("testSingleValueMultipleTimes", testSingleValueMultipleTimes),
        ("testSubparser", testSubparser),
        ("testSubparserBinder", testSubparserBinder),
        ("testSubsubparser", testSubsubparser),
        ("testUpToNextOptionStrategy", testUpToNextOptionStrategy),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArgumentParserTests.__allTests__ArgumentParserTests),
    ]
}
#endif
